site_name: Luis Delatorre
theme:
  name: material
  favicon: assets/images/favicon.ico
  icon:
      logo: material/alpha-d-box
  features:
    - header.autohide
    # - navigation.tabs
    # - navigation.sections
    - navigation.top
    - navigation.indexes
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    # Palette toggle for dark mode
    - scheme: slate 
      toggle:
        icon: octicons/sun-16
        name: Switch to light mode    
      primary: blue
      accent: lime

nav:
  - 'index.md'
  - Projects:
    - 'projects/index.md'
    - Mkdocs Material: 'projects/mkdocs-material.md'
    - Stock Checker: 'projects/stock-checker.md'
    - Home Network: 'projects/home-network.md'
    - Desktop Build: 'projects/desktop-build.md'
  - About Me: 
    - 'bio/index.md'
    

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/luis-delatorre
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ldelatorre
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/luis-a-delatorre/

copyright: |
  &copy; 2023 <a href="https://github.com/luis-delatorre"  target="_blank" rel="noopener">Luis Delatorre</a>